version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Some intialization steps
      - echo ...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Application...  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Load test the application
      - >
        docker run --rm 
        -e NEOLOAD_PROJECT_URL=https://github.com/ohanoun/codepipeline-test/blob/master/neoload-project/Archive/smokeTest.zip?raw=true
        -e NEOLOADWEB_API_URL=http://dockerps4.neotys.com:8080
        -e SCENARIO_NAME=smoke-test-failed 
        -e NEOLOADWEB_TOKEN=0khM5QANVu0rn0BNwRQInGtJ 
        -e TEST_NAME=CI-smoke 
        -e CONTROLLER_ZONE_ID=defaultzone 
        -e LG_ZONE_IDS=defaultzone:1 
        neotys/neoload-web-test-launcher:latest
